### ISSUE TITLE
popModal doesn't animate dialog & drawer (with my setup)

### ISSUE THREAD

**Issue by trompx** [lindesvard/pushmodal#10]
Hi,

I implemented pushmodal in the following way.

**Responsive modal**
```js
export function ModalResponsive({
  trigger,
  title,
  description,
  children = "Modal content",
  open: openDefault = false,
  onClose,
}) {
  const [open, setOpen] = React.useState(openDefault);
  const isDesktop = useIsDesktop();

  React.useEffect(() => {
    if (!open) {
      onClose && onClose();
    }
  }, [open]);
  return isDesktop ? (
    <Dialog open={open} onOpenChange={setOpen}>
      {trigger && <DialogTrigger asChild>{trigger}</DialogTrigger>}
      <DialogContent>
        <DialogHeader className={css({ mb: "3" })}>
          <DialogTitle className={css({ textAlign: "left" })}>
            {title}
          </DialogTitle>
          <DialogDescription className={css({ textAlign: "left" })}>
            {description}
          </DialogDescription>
        </DialogHeader>
        {children}
      </DialogContent>
    </Dialog>
  ) : (
    <Drawer open={open} onOpenChange={setOpen}>
      {trigger && <DrawerTrigger asChild>{trigger}</DrawerTrigger>}
      <DrawerContent
        className={css({
          px: "4",
        })}>
        <DrawerHeader className={css({ textAlign: "left" })}>
          <DrawerTitle>{title}</DrawerTitle>
          <DrawerDescription>{description}</DrawerDescription>
        </DrawerHeader>
        {children}
        <DrawerFooter className={css({ pt: "2" })}>
        </DrawerFooter>
      </DrawerContent>
    </Drawer>
  );
}
```

**Modal**
```js
export default function ModalExample({
  title,
  text,
  customButton,
  onConfirm,
  onCancel,
}) {
  return (
    <>
      <ModalResponsive
        open
        title={title}>
        {text && <div>{text}</div>}
        <div>
          <Button
            variant="outline"
            onClick={() => {
              popModal("Modal");
              onCancel();
            }}>
            Cancel
          </Button>
          {customButton}
          <Button
            variant="destructive"
            onClick={() => {
              popModal("Modal");
              onConfirm();
            }}>
            Yes
          </Button>
        </div>
      </ModalResponsive>
    </>
  );
}
```

The problem I have is that I declare the buttons in the ModalExample that control the open/close state of the modal.
When I first pushmodal to show the ModalExample, it correctly animates. But when I click on the Cancel button and popModal("Modal") triggers, it closes the modal without the nice effect (both with dialog and drawer).
If in ModalResponsive I add the DrawerClose and click on it, it animates correctly:
```js
<DrawerClose asChild>
    <Button variant="default">Cancel</Button>
</DrawerClose>
```

Do you know what could I change so that it animates correctly? I could pass the buttons to the ModalResponsive and wrap them with DrawerClose/DialogClose instead of Button but, in that case I would not leverage popModal at all to close my modals (which defeats the purpose of using pushmodal in the first place).

**Comment by lindesvard** [comment]
Some issues I see in your code

- The library handles the open state what this mean is that you should not define and open state or onOpenChange. This is taken care of in `ModalProvider`. 
- To open a modal you should use the internal functions `createPushModal` returns, so you dont need to define `Trigger` anywhere
-  Your `ModalExample` should only use either `DrawerContent` or `DialogContent` (or better, use `createResponsiveWrapper` https://github.com/lindesvard/pushmodal?tab=readme-ov-file#responsive-rendering-mobiledesktop)

So I think you might have misunderstood how this library works. All your models you create should only have `<(Dialog|Drawer)Content>`, the rest is handled by the `ModalProvider`.

The ModalProvider will wrap your modal with the provided `Wrapper` component. By default this is the `Dialog`.

**Comment by trompx** [comment]
Thanks for the feedbacks and sorry for the delayed answer.
So is there no way to customize the css of the `DialogHeader/Title/Description` etc.? I want to be able to define how the responsive wrapper look like.
I also need to pass an `autofocus` prop to the `DialogContent`, how would I do that with your `createResponsiveWrapper`?

**Comment by trompx** [comment]
Also, I'm using shadow-panda (shadcn with pandacss) and pushmodal doesn't work with the createResponsiveWrapper (getting type errors):
```
Unable to assign type 'ForwardRefExoticComponent<Omit<{ ref?: Ref<never> | undefined; children?: ReactNode; open?: boolean | undefined; defaultOpen?: boolean | undefined; onOpenChange?: ((open: boolean) => void) | undefined; ... 4 more ...; htmlContent?: string | undefined; } & { ...; } & DialogVariantProps, "ref"> & RefAttributes<...>>' to type 'ComponentType<DialogProps>'.
Unable to assign type 'ForwardRefExoticComponent<Omit<{ ref?: Ref<never> | undefined; children?: ReactNode; open?: boolean | undefined; defaultOpen?: boolean | undefined; onOpenChange?: ((open: boolean) => void) | undefined; ... 4 more ...; htmlContent?: string | undefined; } & { ...; } & DialogVariantProps, "ref"> & RefAttributes<...>>' to type 'FunctionComponent<DialogProps>'.
The types of the 'props' and 'props' parameters are incompatible.
Unable to assign type 'DialogProps' to type 'Omit<{ ref?: Ref<never> | undefined; children?: ReactNode; open?: boolean | undefined; defaultOpen?: boolean | undefined; onOpenChange?: ((open: boolean) => void) | undefined; ... 4 more ...; htmlContent?: string | undefined; } & { ...; } & DialogVariantProps, "ref"> & RefAttributes<...>'.
Unable to assign type 'DialogProps' to type 'Omit<{ ref?: Ref<never> | undefined; children?: ReactNode; open?: boolean | undefined; defaultOpen?: boolean | undefined; onOpenChange?: ((open: boolean) => void) | undefined; ... 4 more ...; htmlContent?: string | undefined; } & { ...; } & DialogVariantProps, "ref">'.
Index signature for type “`&[data-part=${string}]`” is missing in type “DialogProps”.ts(2322)
index.d.ts(128, 9): The expected type comes from the 'Wrapper' property, which is declared here on the type '{ Wrapper: ComponentType<DialogProps>; Content: ComponentType<ContentProps>; }'
```

However I can use Dialog and DialogContent directly from shadow-panda instead: 
```js
MyModal: {
    Wrapper: Dialog,
    // Wrapper: Dynamic.Wrapper, -> type error : not working
    Component: MyModal,
},
```
my-modal.tsx
```js
    // <Dynamic.Content> -> type error : not working
    <DialogContent>
```
With this setup, the **animations now work correctly**, but as I mentioned, I now:
- lost the possibility to style the `DialogHeader/Title/Description` etc.
- can't set autofocus or other props
- responsive modal isn't working with non tailwing shadcn components

**Comment by trompx** [comment]
What I ended up doing is to not use the Dynamic.Content. I removed:
```js
<Dialog open={open} onOpenChange={setOpen}>
      {trigger && <DialogTrigger asChild>{trigger}</DialogTrigger>}
```
from my `ModalResponsive` and use it instead of the Dynamic.Content.
I also created an alternative createResponsiveWrapper which returns React.FunctionComponent<WrapperProps> as type.
