### ISSUE TITLE
State hook

### ISSUE THREAD

**Issue by zbeyens** [lindesvard/pushmodal#4]
It would be nice to be able to subscribe to the state of a modal by key. My use-case is to reset a state whenever a modal is opened. I see you're using `state: 'open' | 'close'` but it would probably best to reuse `open: boolean` Radix's API. Something like:

```ts
// no key for any opened modal, or could export another hook useAllModalsState
// useModalState or useModalOpenState or useModalOpen
const useModalState = (key?: T) => {
  // return the open state of the modal with that key
  return open
}
```

That may require the provider to have children, which would be a more intuitive API since most providers are designed like that. You can prevent the re-rendering by nesting the `ModalProvider` content one level down so only that child will be re-rendered on modal state change:

```tsx
const ModalContext = React.createContext(...)

const Modal = () => {} // previous ModalProvider implementation

const ModalProvider = () => {  
  return (
    <ModalContext.Provider>
      <Modal />
      {children}
    </ModalContext.Provider>
  )
}
```

**Comment by lindesvard** [comment]
Will add this to the next version. But global event listener and a hook where you can see if its open or not.

No need of using a context & provider since I use events.

**Comment by lindesvard** [comment]
Should be solved in latest version. Below is taken from readme.

---

You can listen to events with `useOnPushModal` (inside react component) or `onPushModal` (or globally).

The event recieve the state of the modal (open/closed), the modals name and props. You can listen to all modal changes with `*` or provide a name of the modal you want to listen on.

**Inside a component**

```tsx
import { useCallback } from 'react'
import { useOnPushModal } from '@/modals'

// file: a-react-component.tsx
export default function ReactComponent() {
  // listen to any modal open/close
  useOnPushModal('*', 
    useCallback((open, props, name) => {
      console.log('is open?', open);
      console.log('props from component', props);
      console.log('name', name);
    }, [])
  )
  
  // listen to `ModalExample` open/close
  useOnPushModal('ModalExample', 
    useCallback((open, props) => {
      console.log('is `ModalExample` open?', open);
      console.log('props for ModalExample', props);
    }, [])
  )
}
```

**Globally**

```ts
import { onPushModal } from '@/modals'

const unsub = onPushModal('*', (open, props, name) => {
  // do stuff
})
```

**Comment by zbeyens** [comment]
Awesome! Since we use `pop` to close modals, `onPush` intuitively means it's called only on push (`open = true`). Perhaps naming something like `onModalChange` would cover all the states?
